name: "webhook"
repository: github.com/simar7/trivy-plugin-webhook
version: "0.2.2"
usage: send trivy results to a webhook
description: |-
  A Trivy plugin that sends trivy results to a webhook. 
  Usage: trivy webhook TYPE[.VERSION][.GROUP] NAME
platforms:
  - selector: # optional
      os: darwin
      arch: amd64
    uri: ./trivy-webhook # where the execution file is (local file, http, git, etc.)
    bin: ./trivy-webhook # path to the execution file
  - selector: # optional
      os: linux
      arch: amd64
    uri: https://github.com/simar7/trivy-plugin-webhook/releases/download/v0.2.2/trivy-webhook.tar.gz
    bin: ./trivy-webhook
  - selector:
      os: darwin
      arch: arm64
    uri: ./trivy-webhook
    bin: ./trivy-webhook
